version: '3.8'
services:
  app:
    build: .
    container_name: user_microservice
    ports:
      - "8090:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: