spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_service
    username: postgres
    password: postgres

    jpa:
      database-platform: org.hibernate.dialect.PostgreSqlDialect
      hibernate:
        ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          format_sql: true

server:
  port: 8082

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html