spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: postgres

    jpa:
      database-platform: org.hibernate.dialect.PostgreSqlDialect
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8080

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml